# Generated by Django 5.2.18 on 2026-10-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=150, verbose_name="name")),
                ("description", models.TextField(blank=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Shop, brand or pharmacy you got it from.",
                        max_length=120,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Batch, lot or receipt number.",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LISTED", "Listed for sale"),
                            ("SOLD", "Sold"),
                            ("USED", "Used"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="items.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "item_name"],
            },
        ),
    ]
