# Generated by Django 5.2.18 on 2026-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_default_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="items/", verbose_name="photo"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="What it cost you. Used for listings and your impact totals.",
                max_digits=10,
                verbose_name="value",
            ),
        ),
    ]
