# Generated by Django 5.2.18 on 2026-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/", verbose_name="profile picture"
            ),
        ),
    ]
