# Generated by Django 5.2.18 on 2026-10-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SAVED", "Saved (used in time)"),
                            ("SOLD", "Sold on marketplace"),
                            ("LOST", "Lost (expired)"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("resolved_date", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_records",
                        to="items.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impact_records",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-resolved_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImpactSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "total_saved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_lost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "impact summaries",
                "ordering": ["-year"],
                "unique_together": {("user", "year")},
            },
        ),
    ]
