# Generated by Django 5.2.18 on 2026-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactrecord",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("SAVED", "Saved (used in time)"),
                    ("SOLD", "Sold in the shop"),
                    ("LOST", "Lost (expired)"),
                ],
                max_length=5,
            ),
        ),
    ]
